export enum ExternalSystemActionType {
  GET_EXTERNALSYSTEM_LIST = 'GET_EXTERNALSYSTEM_LIST',
  GET_EXTERNALSYSTEM      = 'GET_EXTERNALSYSTEM',
  UPDATE_EXTERNALSYSTEM   = 'UPDATE_EXTERNALSYSTEM',
  INSERT_EXTERNALSYSTEM   = 'INSERT_EXTERNALSYSTEM',
  CHECK_EXTERNALSYSTEM    = 'CHECK_EXTERNALSYSTEM',
  APPROVE_EXTERNALSYSTEM  = 'APPROVE_EXTERNALSYSTEM',
  REJECT_EXTERNALSYSTEM   = 'REJECT_EXTERNALSYSTEM',
}
