export enum TransactionFeeActionType {
  GET_TRANSACTION_FEE_LIST = 'GET_TRANSACTION_FEE_LIST',
  GET_TRANSACTION_FEE      = 'GET_TRANSACTION_FEE',
  UPDATE_TRANSACTION_FEE   = 'UPDATE_TRANSACTION_FEE',
  INSERT_TRANSACTION_FEE   = 'INSERT_TRANSACTION_FEE',
  CHECK_TRANSACTION_FEE    = 'CHECK_TRANSACTION_FEE',
  APPROVE_TRANSACTION_FEE  = 'APPROVE_TRANSACTION_FEE',
  REJECT_TRANSACTION_FEE   = 'REJECT_TRANSACTION_FEE',
}
