const ContentResourceEN = {
  image_list: 'Content Image',
  image_id: 'Id',
  image_title: 'Image',
  image_seq: 'Sequence',
  image_name: 'Image Name',
  image_choose_file: 'Choose File Image',
  image_thumbnail: 'Thumbnail',
  image_update_date: 'Updated Date',
  image_th_desc: 'Description TH',
  image_en_desc: 'Description EN',
  image_allow_unfollow: 'allowUnfollow',
  image_remark: 'Remark',
  placeholder_image_id: 'Id',
  placeholder_image_sequence: 'Sequence',
  category_title: 'Category',
  category_seq: 'Sequence',
  category_id: 'Id',
  category_th_desc: 'Description TH',
  category_en_desc: 'Description EN',
  category_allow_unfollow: 'Allow Unfollow',
  category_list: 'Content Categories',
  article: 'Article',
  article_title: 'Title',
  article_keyword: 'Keyword',
  article_description: 'Description',
  article_status: 'Status',
  article_active: 'Status',
  article_inactive: 'InActive',
  drive_id: 'Id',
  drive: 'Drive',
  drive_name: 'Name',
  drive_owners: 'Owners',
  drive_modified_time: 'Modified Time',
  drive_size: 'Size',
  action: 'Action',
  comment_title: 'Comments',
  close: 'Close',
  button_save: 'Save',
};

export default ContentResourceEN;
