export enum PayerActionType {
  GET_PAYER_LIST = 'GET_PAYER_LIST',
  GET_PAYER      = 'GET_PAYER',
  UPDATE_PAYER   = 'UPDATE_PAYER',
  INSERT_PAYER   = 'INSERT_PAYER',
  CHECK_PAYER    = 'CHECK_PAYER',
  APPROVE_PAYER  = 'APPROVE_PAYER',
  REJECT_PAYER   = 'REJECT_PAYER',
}
