const ReportResourcesVI = {
  // user activity log
  user_activity_log_search: 'Audit Trail - User Search',
  user_activity_log_IP: 'IP',

  // Payment Acount
  payment_subject: 'Payment Account',
  payment_list: 'Payment Account Summary',
  //// Payment_detail_search_form
  payment_detail_search_title: 'Payment Detail Search',
  payment_detail_search_date_from: 'Payment Date From',
  payment_detail_search_date_to: 'Payment Date To',
  payment_detail_search_transaction_no: 'Transaction No.',
  payment_detail_search_payment_status: 'Payment Status',
  payment_detail_search_payment_mode: 'Payment Mode',
  payment_detail_search_enternal_system_reference_number: 'Enternal System Reference Number',
  payment_detail_search_ex_sys_reference_num: 'External System Reference Number',
  payment_detail_search_payer_consumer: 'Payer/Consumer',
  payment_detail_search_currency: 'Currency',
  payment_detail_search_debit_acc_no: 'Debit Account No.',
  payment_detail_search_tran_id: 'Transaction ID',
  payment_detail_search_tran_date: 'Transaction Date',
  payment_detail_search_history: 'History',
  //// enable for night mode
  enable_for_night_mode: 'Enable For Night Mode',

  // Transaction Log
  audit_trail_transaction_search: 'Audit Trail - Transaction Search',
  transaction_payment_amount: 'Payment Amount',
  transaction_last_status: 'Last Status',
  transaction_payment_date_from: 'Payment Date From',
  transaction_payment_date_to: 'Payment Date To',
  transaction_amount_first: 'Amount first',
  transaction_amount_second: 'Amount second',
  transaction_log_amount: 'Amount',
  transaction_log_currency: 'Currency',
  transaction_log_description: 'Description',

  // Fee Detail Report
  fee_detail_report_tile_summary: 'Fee Transaction Detail Report Summary',
  fee_detail_report_tile: 'Fee Transaction Detail',
  fee_detail_report_search_data: 'Search Data',
  fee_detail_report_customer: 'Customer',
  fee_detail_report_entity_select: 'Entity Select',
  fee_detail_report_entity_name: 'Entity Name',
  fee_detail_report_entity_name_to: 'Entity Name To',
  fee_detail_report_fee_status: 'Fee Status',
  fee_detail_report_processed: 'Processed',
  fee_detail_report_unprocessed: 'Unprocessed',
  fee_detail_report_date: 'Date',
  fee_detail_report_payment_transaction_date: 'Payments Transaction Date',
  fee_detail_report_to_day: 'Today',
  fee_detail_report_before_to_day: 'Before Today',
  fee_detail_report_fee_effective_day: 'Fee Effective Day',
  fee_detail_report_fee_debit_account: 'Fee Debit Account',
  fee_detail_report_view_summary: 'View Summary',
  fee_detail_report_list_transaction_date: 'Transaction Date',
  fee_detail_report_list_transaction_exffective_date: 'Transaction Effective Date',
  fee_detail_report_list_transaction_no: 'Transaction No',
  fee_detail_report_list_internal_reference: 'Internal Reference',
  fee_detail_report_list_transaction_status: 'Transaction Status',
  fee_detail_report_list_transaction_amount: 'Transaction Amount (THB)',
  fee_detail_report_list_fee_amount: 'Fee Amount (THB)',
  fee_detail_report_list_fee_transaction_no: 'Fee Transaction No',
  fee_detail_report_list_fee_positing_type: 'Fee Positing Type',
  fee_detail_report_list_debit_account: 'Debit Account (Fee)',
  fee_detail_report_list_payer: 'To add to payer list',

  // Web Service Trans
  web_services_trans_search: 'Audit Trail - Web Services Transaction Search',
  corr_id: 'CorrID',
  externalsys_ref_no: 'External System Referance Number',
  transNo: 'Transaction Number',
  web_services_type: 'Web Services Type',
  receive_date: 'Receive Date',
  receive_date_from: 'Receive Date From',
  receive_date_to: 'Receive Date To',
  web_services_trans_detail: 'Web Services Transaction Log Detail',
  // Balance Inquiry
  account_type: 'Account Type',
  account_balance: 'Account Balance',
  balance_enquiry_list: 'Balance Enquiries',
};

export default ReportResourcesVI;
