export enum PayeeActionType {
  GET_PAYEE_LIST                          = 'GET_PAYEE_LIST',
  GET_ALL_DYNAMIC_FORM                    = 'GET_ALL_DYNAMIC_FORM',
  GET_DYNAMIC_FORM_BY_MODEL_NAME          = 'GET_DYNAMIC_FORM_BY_MODEL_NAME',
  GET_DYNAMIC_FORM_BY_ID                  = 'GET_DYNAMIC_FORM_BY_ID',
  INSERT_DYNAMIC_FORM                     = 'INSERT_DYNAMIC_FORM',
  UPDATE_DYNAMIC_FORM                     = 'UPDATE_DYNAMIC_FORM',
  DELETE_DYNAMIC_FORM                     = 'DELETE_DYNAMIC_FORM',
  GET_PAYEE                               = 'GET_PAYEE',
  UPDATE_PAYEE                            = 'UPDATE_PAYEE',
  INSERT_PAYEE                            = 'INSERT_PAYEE',
  CHECK_PAYEE                             = 'CHECK_PAYEE',
  APPROVE_PAYEE                           = 'APPROVE_PAYEE',
  REJECT_PAYEE                            = 'REJECT_PAYEE',
}
